### ISSUE TITLE
Update ProjLint when running `tools install`

### ISSUE THREAD

**Issue by smnbck** [JamitLabs/ProjLint#30]
@Dschee When running `tools install` ProjlLint won't be updated. Due to the recent addition of the `--strict` flag in ProjLint the `ci lint` command failed for me so I had to update it by myself. This is not a big issue but updating ProjLint when running `tools install` would ensure an even smoother experience imo.

**Comment by Jeehut** [comment]
The reason why it wasn't working is probably due to you having `projlint` already installed via Mint. We could add a step to run `mint uninstall JamitLabs/ProjLint` before doing so, but that would definitely need to go into the https://github.com/JamitLabs/NewProjectTemplate-iOS project, not this one. So closing this. ;)

Feel free to post a PR with the fix.
